spring:
  application:
    name: jira-task-creator

jira:
  url: ${JIRA_URL}    //отредактировать, вставить реальные данные
  username: ${JIRA_USERNAME}    //отредактировать, вставить реальные данные
  token: ${JIRA_TOKEN}    //отредактировать, вставить реальные данные
  project:
    key: ${JIRA_PROJECT_KEY}    //отредактировать, вставить реальные данные